---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos/systemd
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: True
  env:
    ANSIBLE_ROLES_PATH: ../../../
    # ANSIBLE_ROLES_PATH: /home/vagrant/python2-venv/roles/ansible-files/roles/
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
  test_sequence:
    # - lint
    - destroy
    # - dependency
    - syntax
    - create
    # - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - destroy
